### ISSUE TITLE
How da

### ISSUE THREAD

**Issue by grillermo** [adammck/bam#1]
I'm sorry if this is a dead project, but i tried using it with not luck.

First the instructions in the README are not updated but i manage to run bam moving the bin/bam to root dir of the project and running python bam then i tried the symlink and went to the url to no avail. Tried going to the server address 127.0.0.1:30559 but then got this exception:

```
Exception happened during processing of request from ('127.0.0.1', 59068)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 639, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 343, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 331, in handle_one_request
    method()
  File "/Users/grillermo/myapps/bam/bam/handler.py", line 8, in do_GET
    resp = self.app().request(self.path, dict(self.headers))
  File "/Users/grillermo/myapps/bam/bam/app.py", line 96, in request
    if not self.is_running():
  File "/Users/grillermo/myapps/bam/bam/app.py", line 88, in is_running
    return self.proc and (self.proc.status_code is None)
  File "/Users/grillermo/.virtualenvs/bandtastic/lib/python2.7/site-packages/envoy/core.py", line 80, in status_code
    if self._status_code is not None:
AttributeError: 'ConnectedCommand' object has no attribute '_status_code'
```

BTW the dnsmasq installation went ok.

Again, i'm sorry if this is a dead project, i'll close the issue if thats the case.

**Comment by jfrux** [comment]
Wish it wasn't dead tho...

**Comment by adammck** [comment]
I'm afraid that I don't use Django much these days, so have let this thing fall into disrepair. I'm not even sure that it works with a modern Python. I'd be happy to add maintainers, if anyone cares to resurrect it.

**Comment by jfrux** [comment]
But you’re saying at some point, it did mimic the Pow functionality quite nicely on Mac?

**Comment by adammck** [comment]
Yes, I used it for quite a while, until I moved on to (gasp!) Rails. It's just an HTTP proxy which runs `manage.py runserver` in the `blah` directory the first time it receives a request to `blah.bam`, and forwards requests there. Some stuff about ENV files, too. Nothing fancy. I don't think it ever bothered to _stop_ the server, though...

**Comment by jfrux** [comment]
Nice… well no worries… the only people looking for this tool are people who use Rails. :)
I’m a Rails developer that is having to do Django dev…

Seems like the Django community just doesn’t care about shit like this sadly…
I really wish they cared more about developer on-boarding experience like the Ruby community does.

The experience getting started just feels better from the Rails perspective in my opinion… but I’m sure some would argue the opposite too.
